### ISSUE TITLE
Does not send successfully unless I wait 30 seconds

### ISSUE THREAD

**Issue by countergram** [sematext/winston-logsene#11]
I just started trying to use the example code with my test Logsene instance. Flush on exit does not appear to be working. So far the only way I've been able to get a log message to be sent in a barebones Node script is to add a 30-second timeout after the log (after reading through the source and seeing the periodic send call). I also read issue #10 and tried the workaround there with the dummy console transport, and have not been successful.

Based on my console.logs, send() of the underlying Logsene object is getting called on exit, but the callback from the http request never executes.

I have winston-logsene 1.2.0, winston 2.2.0, node 6.6.0. Thanks.

(To try to simplify the issue I went a layer down. The following works consistently.)
```
var Logsene = require('logsene-js');
var logger = new Logsene(process.env.LOGSENE_TOKEN);

logger.log('info', 'exit hook');

process.on('beforeExit', function () {
  if (logger.logCount) {
    logger.send();
  }
});
```

**Comment by megastef** [comment]
Did you set options.flushOnExit=true in the winston constructor?

**Comment by countergram** [comment]
I tried setting `flushOnExit: true` in the `add` call and have now tried it on the `Winston` constructor as well. No change. It defaults to `true`, and in fact I don't think it can be set to `false`:

```
if (!options.flushOnExit) {
    options.flushOnExit = true
}
```

**Comment by megastef** [comment]
Please let me know, how to reproduce it. How is your program terminated? Calling process.exit (which means no async code can be executed)?

Could you please post the output of ```npm ls``` - so we can check dependencies? 

Here is what I did:
1) Run the example https://github.com/sematext/winston-logsene/blob/master/example/index.js
```node exaple/index.js````
Output: 
```
node example/index.js 
2016-09-25T17:58:36.327Z winston-logsene: start flushing 1 logs before exit ...
2016-09-25T17:58:36.788Z winston-logssene: flush before exit: 1 logs send.
2016-09-25T17:58:36.989Z winston-logsene: flush: no logs in buffer
```

Check logs in Logsene: 

![bildschirmfoto 2016-09-25 um 20 04 16](https://cloud.githubusercontent.com/assets/7289505/18817201/4bd3040c-835b-11e6-8d49-84a30d6cfba6.png)

and Kibana
![bildschirmfoto 2016-09-25 um 20 03 00](https://cloud.githubusercontent.com/assets/7289505/18817203/590407de-835b-11e6-99f7-38a3522452a1.png)

**Comment by megastef** [comment]
Should be fixed, something changed in logsene-js log counts, and winston-logsene should watch own logCounts. https://github.com/sematext/winston-logsene/commit/3a967abec30b5e4dfd7e53dc40e435ace5e8d338

**Comment by countergram** [comment]
I tried with 1.2.1 and it works for me now. Thanks.
