### ISSUE TITLE
Add instructions for EU instance

### ISSUE THREAD

**Issue by Notifium** [sematext/winston-logsene#12]
Hi,
I've been trying to get the logs writing to the EU instance, but couldn't get it working. I've resorted to create an account on the US instance and it's working fine. Could you include instructions for configuring the module for the EU please?
Regards,
Andy

**Comment by otisg** [comment]
Hi Andy.
> url - Logsene receiver URL (e.g. for Logsene On Premises), defaults to 'https://logsene-receiver.sematext.com/_bulk'
I think all you need to do is specify the URL for the Logsene Receiver in Sematext Cloud Europe: https://logsene-receiver.eu.sematext.com/_bulk

Do things work for you if you do that?

**Comment by Notifium** [comment]
Hi Otis,
Thanks for getting back to me. Yes, I think you're right, but I can't work out where to put that URL. I'm assuming some sort of options object, but I can't only find those mentioned in the core logsene-js library, not this one.
Andy

**Comment by Notifium** [comment]
Oh dear lord, I'm such an idiot! I've seen it now:

logger.add (logsene, {token: 'xxx', type: 'test_logs', url: 'https://logsene-receiver.eu.sematext.com/_bulk'});

Thanks for the pointer.

Andy

**Comment by megastef** [comment]
@Notifium thanks for reporting. We just changed the README and added URL in code example and listed EU receiver URL in the description for the "url"  parameter.

**Comment by Notifium** [comment]
No problem. Thanks for the quick response.
