### ISSUE TITLE
Unhandled error when unreachable is causing crash

### ISSUE THREAD

**Issue by FredyC** [sematext/winston-logsene#22]
The service is/was down and it caused crash in our app running on Heroku. Am I doing something wrong somewhere? I certainly don't want to try/catch every logging attempt 🙈 

![image](https://user-images.githubusercontent.com/1096340/88932503-7478af80-d27e-11ea-8d04-0c96e3ccf433.png)

**Comment by otisg** [comment]
I think the improvement for this was added in https://github.com/sematext/winston-logsene/commit/32b91403435cae295f03a44f6a872558d53d6c39 
There was a release made after that.  Could you try that one?

**Comment by FredyC** [comment]
I take it back, problem is still the same. I suppose it's a different kind of error than `EAI_AGAIN`.

**Comment by adnanrahic** [comment]
Hey @FredyC ! I've released version [2.0.11](https://github.com/sematext/winston-logsene/releases/tag/2.0.11) with a fix for this. Can you please check it out and confirm it fixes your issue?

**Comment by FredyC** [comment]
@adnanrahic Thanks, I will upgrade, but I guess it would be hard to confirm as it kinda needs Logsene to be down which happens rarely. However, your code change to emit a warning makes sense, so hopefully, it will be alright 🤞
